### ISSUE TITLE
error during make ubunu 18.04

### ISSUE THREAD

**Issue by fp30** [gerbilvis/gerbil#38] opened 2018-09-20 21:41 UTC
Hi, I am getting an error at the end of the make script that reads
[ 97%] Linking CXX executable ../../bin/qgerbil
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
gerbil-master/gui/CMakeFiles/qgerbil.dir/build.make:277: recipe for target 'bin/qgerbil' failed
make[2]: *** [bin/qgerbil] Error 1
CMakeFiles/Makefile2:446: recipe for target 'gerbil-master/gui/CMakeFiles/qgerbil.dir/all' failed
make[1]: *** [gerbil-master/gui/CMakeFiles/qgerbil.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
Can you help with this?
Thanks

**Comment by ypnos** [comment] 2018-09-21 21:17
I can confirm the problem, I guess it is caused by some change in CMake, but not sure yet.

**Comment by ypnos** [comment] 2018-09-22 09:39
I committed a fix, please try current master. Thank you!

**Comment by fp30** [comment] 2018-09-22 11:59
works now, thanks!

**Closed as completed** 2018-09-22 11:59 UTC
